exp_name: qwen2p5-coder-3b-dockersft5k
output_dir: /us3/yuandl/ckpt/${exp_name}
model:
  _component_: torchtune.models.qwen2_5.qwen2_5_3b
tokenizer:
  _component_: torchtune.models.qwen2_5.qwen2_5_tokenizer
  path: /us3/yuandl/models/SWE-bench/Qwen/Qwen2.5-Coder-3B-Instruct/vocab.json
  merges_file: /us3/yuandl/models/SWE-bench/Qwen/Qwen2.5-Coder-3B-Instruct/merges.txt
  max_seq_len: 32768
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /us3/yuandl/models/SWE-bench/Qwen/Qwen2.5-Coder-3B-Instruct
  checkpoint_files:
  - model-00001-of-00002.safetensors
  - model-00002-of-00002.safetensors
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN2
  safe_serialization: true
resume_from_checkpoint: false
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: json
  data_files: /us3/yuandl/SWE_resource/CentOs/D/SWE/datasets/docker4000/balanced_data.json
  split: train
  conversation_column: messages
  conversation_style: openai
  train_on_input: false
  new_system_prompt: null
  packed: false
seed: 42
shuffle: true
batch_size: 1
optimizer:
  _component_: torch.optim.AdamW
  fused: true
  weight_decay: 0.01
  lr: 0.0001
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 5
optimizer_in_bwd: true
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
epochs: 2
max_steps_per_epoch: null
gradient_accumulation_steps: 1
compile: true
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: swesmith
  group: ${exp_name}
  job_type: full_finetune_distributed
log_every_n_steps: 1
log_peak_memory_stats: true
device: cuda
dtype: bf16
enable_activation_checkpointing: true
enable_activation_offloading: false
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: false
  output_dir: ${output_dir}/profiling_outputs
  cpu: true
  cuda: true
  profile_memory: false
  with_stack: false
  record_shapes: true
  with_flops: false
  wait_steps: 5
  warmup_steps: 5
  active_steps: 2
  num_cycles: 1
